spring.application.name=springboot-learning
server.port = 8081

spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update

name.prefix=Mr.
name.suffix=You are too good.

spring.mvc.apiversion.use.path-segment=1
#spring.mvc.apiversion.use.header=X-API-Version
#spring.mvc.apiversion.use.query-parameter=version
#spring.mvc.apiversion.default=1.0.0